# Generated by Django 5.1.6 on 2025-08-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_id', models.IntegerField(default=99999)),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('reporting_line', models.CharField(max_length=100)),
                ('onboard_date', models.DateField()),
            ],
        ),
    ]
