# Generated by Django 5.1.6 on 2025-08-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asserts_manager', '0002_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='onboard_date',
            field=models.CharField(max_length=100),
        ),
    ]
