# Generated by Django 5.1.6 on 2025-10-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asserts_manager', '0004_department_asset_alter_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(choices=[('SHA', '上海'), ('NGB', '宁波'), ('SZX', '深圳')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='mail',
            field=models.CharField(default='', max_length=100),
        ),
    ]
