# Generated by Django 5.1.6 on 2025-11-11 01:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asserts_manager', '0005_employee_city_employee_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='department',
        ),
        migrations.AddField(
            model_name='asset',
            name='city',
            field=models.CharField(choices=[('SHA', 'Shanghai'), ('NGB', 'Ningbo'), ('SZX', 'Shenzhen')], default='SHA', max_length=10),
        ),
        migrations.AddField(
            model_name='asset',
            name='description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.CharField(choices=[('SHA', 'Shanghai'), ('NGB', 'Ningbo'), ('SZX', 'Shenzhen')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='reporting_line',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
