# Generated by Django 5.1.6 on 2025-11-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asserts_manager', '0006_remove_asset_department_asset_city_asset_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.CharField(choices=[('thinkpad14', 'Thinkpad丨 ThinkBook 14丨 I5-1135G7 丨512-SSD 丨 14')], default='thinkpad14', max_length=20),
        ),
    ]
