# Generated by Django 5.1.6 on 2025-11-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asserts_manager', '0007_alter_asset_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='name',
        ),
    ]
