# Generated by Django 5.1.6 on 2025-11-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asserts_manager', '0008_remove_asset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='file',
            field=models.FileField(default=1, upload_to='autopilot_csv/assets/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='hostname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
