# Generated by Django 5.1.6 on 2025-11-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asserts_manager', '0009_asset_file_asset_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(null=True, upload_to='autopilot_csv/assets/'),
        ),
    ]
