# Generated by Django 5.1.6 on 2025-11-11 08:25

import asserts_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asserts_manager', '0010_alter_asset_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=asserts_manager.models.asset_upload_path),
        ),
    ]
